import React, { useEffect, useState } from 'react';
import '../css/management.css';
import { translateText } from './i18n';

async function api(request, path, method = 'GET', body) {
  const response = await request(path, { method, ...(body ? { body: JSON.stringify(body) } : {}) });
  const data = response.status === 204 ? null : await response.json();
  if (!response.ok) throw new Error(Object.values(data?.errors || {}).flat()[0] || data?.message || 'Não foi possível salvar.');
  return data;
}
const money = value => Number(value || 0).toLocaleString(document.documentElement.lang || 'pt-BR', { style: 'currency', currency: 'BRL' });
const minutes = value => `${Math.floor(Number(value || 0) / 60)}h ${Number(value || 0) % 60}min`;
export function Editor({ title, fields, initial, onSave, onClose }) {
  const [form, setForm] = useState(initial || {}), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  useEffect(() => { const dialog = document.getElementById('management-editor'); dialog.showModal(); return () => dialog.close(); }, []);
  return <dialog id="management-editor" className="management-dialog" onCancel={e => { e.preventDefault(); if (!busy) onClose(); }}><form noValidate onSubmit={async e => { e.preventDefault(); setError(''); const missing=fields.find(field=>field.required&&!String(form[field.key]??'').trim()); if(missing)return setError(missing.requiredMessage||`Informe ${missing.label.toLocaleLowerCase('pt-BR')}.`); const tooShort=fields.find(field=>field.minLength&&String(form[field.key]??'').trim().length<field.minLength); if(tooShort)return setError(tooShort.minLengthMessage||`${tooShort.label} deve ter pelo menos ${tooShort.minLength} caracteres.`); setBusy(true); try { await onSave(form); onClose(); } catch (e) { setError(e.message); } finally { setBusy(false); } }}>
    <header><h2>{title}</h2><button type="button" disabled={busy} aria-label="Fechar" onClick={onClose}>×</button></header>
    <div className="management-fields">{fields.map(field => <label key={field.key}><span>{field.label}</span>{field.options ? <select aria-label={field.label} required={field.required} disabled={field.disabled} value={form[field.key] ?? ''} onChange={e => setForm({ ...form, [field.key]: e.target.value })}><option value="">Selecione</option>{field.options.map(option => <option key={option.id} value={option.id} translate="no">{option.name}</option>)}</select> : <input aria-label={field.label} required={field.required} disabled={field.disabled} type={field.type || 'text'} min={field.min} max={field.max} step={field.step} minLength={field.minLength} maxLength={field.maxLength || 2000} value={form[field.key] ?? ''} onChange={e => setForm({ ...form, [field.key]: e.target.value })} />}{field.help&&<small className="management-field-help">{field.help}</small>}</label>)}</div>
    {error && <p role="alert">{error}</p>}<footer><button type="button" disabled={busy} onClick={onClose}>Cancelar</button><button className="primary-action" disabled={busy}>{busy ? 'Salvando...' : 'Salvar'}</button></footer>
  </form></dialog>;
}
export function FinancialResult({ data }) {
  if (!data) return null;
  const rows = [['Receita', 'total_revenue', 'revenue'], ['Impostos', 'taxes', 'taxes'], ['Comissão', 'commission', 'commission'], ['Custo dos analistas', 'labor_cost', 'labor_cost'], ['Custos adicionais', 'approved_expenses', 'additional_cost'], ['Custo total', 'operating_costs', 'operating_costs'], ['Lucro', 'profit', 'profit'], ['Margem (%)', 'margin_percent', 'margin_percent']];
  const highlights = [['Receita realizada', data.actual.total_revenue], ['Custo total', data.actual.operating_costs], ['Lucro realizado', data.actual.profit], ['Margem', data.actual.margin_percent, true]];
  return <section className="management-report"><header className="report-heading"><div><span>Visão financeira</span><h2>Resultado do projeto</h2><p>Comparativo entre o planejamento e os valores realizados.</p></div><span className="activity-count">{data.activities_count} {data.activities_count === 1 ? 'atividade' : 'atividades'}</span></header>{data.complete === false && <p role="alert">Resultado parcial: existem atividades sem tarifa vigente. Cadastre o custo/hora dos analistas.</p>}
    <div className="report-highlights">{highlights.map(([label,value,percent])=><article key={label}><span>{label}</span><strong>{percent ? `${value ?? '—'}${value == null ? '' : '%'}` : money(value)}</strong></article>)}</div>
    <div className="report-table"><table><thead><tr><th>Indicador</th><th>Planejado</th><th>Realizado</th></tr></thead><tbody>{rows.map(([label,actual,estimated]) => <tr key={actual}><th>{label}</th><td>{actual === 'margin_percent' ? (data.estimated[estimated] ?? '—') : money(data.estimated[estimated])}</td><td>{actual === 'margin_percent' ? (data.actual[actual] ?? '—') : money(data.actual[actual])}</td></tr>)}<tr><th>Tempo</th><td>{minutes(data.estimated.minutes)}</td><td>{minutes(data.actual.worked_minutes)}</td></tr><tr><th>Horas consumidas (%)</th><td>100</td><td>{data.actual.estimated_minutes_consumed_percent ?? '—'}</td></tr></tbody></table></div>
    <div className="report-breakdowns">{[['Por analista', data.by_analyst], ['Por tipo de atividade', data.by_activity_type]].map(([title,items]) => <section key={title}><h3>{title}</h3>{items?.length ? <><table><thead><tr><th>Nome</th><th>Tempo</th><th>Custo</th></tr></thead><tbody>{items.map((item,i) => <tr key={i}><td translate="no">{item.name}</td><td>{minutes(item.minutes)}</td><td>{money(item.cost)}</td></tr>)}</tbody></table><div className="management-bars">{items.map((item,i) => <div key={i}><span translate="no">{item.name}</span><meter aria-label={item.name} min="0" max={Math.max(1, ...items.map(x=>Number(x.cost)))} value={Number(item.cost)} /><span>{money(item.cost)}</span></div>)}</div></> : <div className="management-empty"><strong>Nenhum dado disponível</strong><span>Os dados aparecerão após o registro das atividades.</span></div>}</section>)}</div>
    <div className="report-footer-grid"><section><h3>Lucros e custos</h3><div className="management-bars">{[["Lucro",data.actual.profit],["Custos",data.actual.total_deductions]].map(([label,value])=><div key={label}><span>{label}</span><meter aria-label={label} min={Math.min(0,Number(data.actual.profit||0))} max={Math.max(1,Number(data.actual.profit||0),Number(data.actual.total_deductions||0))} value={Number(value||0)}/><span>{money(value)}</span></div>)}</div></section><section><h3>Custos adicionais aprovados</h3>{data.expenses?.length ? <div className="approved-expenses">{data.expenses.map((item,i)=><p key={i}><span translate="no">{item.description}</span><strong>{money(item.amount)}</strong></p>)}</div> : <div className="management-empty compact"><span>Nenhum custo adicional aprovado.</span></div>}</section></div>
  </section>;
}
const rateFields = [{key:'user_id',label:'Analista',required:true}, {key:'normal_cost_rate',label:'Custo/hora normal',type:'number',min:0,step:'0.01',required:true}, {key:'overtime_cost_rate',label:'Custo/hora extra',type:'number',min:0,step:'0.01',required:true}, {key:'overtime_sale_rate',label:'Venda/hora extra',type:'number',min:0,step:'0.01',required:true}, {key:'effective_from',label:'Vigência inicial',type:'date',required:true}, {key:'effective_until',label:'Vigência final',type:'date'}];
export function ProjectWorkspace({ request, onNewProject }) {
  const [projects,setProjects]=useState([]), [access,setAccess]=useState({}), [parameters,setParameters]=useState({}), [error,setError]=useState(''), [search,setSearch]=useState(''), [selected,setSelected]=useState(null), [detail,setDetail]=useState(null), [expenses,setExpenses]=useState([]), [financial,setFinancial]=useState(null), [editor,setEditor]=useState(null), [busy,setBusy]=useState(false);
  async function load() { try { const [p,a] = await Promise.all([api(request,'/projects'),api(request,'/management/access')]); setProjects(p); setAccess(a); if(a['parameters.view']) setParameters(await api(request,'/parameters')); } catch(e){setError(e.message);} }
  useEffect(()=>{load();},[]);
  async function open(project) { setError(''); setSelected(project); setDetail(null); setExpenses([]); setFinancial(null); try { if(access['projects.update']||access['financial.view']) setDetail(await api(request,`/projects/${project.id}/configuration`)); setExpenses(await api(request,`/projects/${project.id}/expenses`)); if(access['financial.view'])setFinancial(await api(request,`/projects/${project.id}/financial-result`)); }catch(e){setError(e.message);} }
  async function refresh() { await load(); if(selected) await open(selected); }
  function editProject(project) {
    const definitions = [['name','Nome do projeto'],['proposal_number','Número da proposta'],['proposal_date','Data da proposta','date'],['client_id','Cliente','select','clients'],['project_status_id','Status','select','project_statuses'],['project_situation_id','Situação','select','project_situations'],['account_manager_id','Gerente de contas','select','users'],['project_manager_id','Gerente do projeto','select','users'],['start_date','Data de início','date'],['end_date','Data de término','date'],['billing_date','Data de faturamento','date'],['contract_value','Valor do projeto','number'],['commission_rate','Comissão (%)','number'],['estimated_labor_cost','Custo estimado do analista','number'],['estimated_additional_cost','Custo adicional estimado','number'],['estimated_hours','Horas estimadas','number'],['estimated_remaining_minutes','Minutos estimados','number']];
    const fields=definitions.filter(([key])=>parameters.field_access?.[key]?.view!==false).map(([key,label,type,list])=>({key,label,type:type==='select'?undefined:type,options:list?parameters[list]||[]:undefined,required:['name','proposal_number','project_status_id','project_situation_id','contract_value'].includes(key),min:type==='number'?0:undefined,step:type==='number'?'0.01':undefined,disabled:parameters.field_access?.[key]?.edit===false||!access['financial.manage']&&['contract_value','commission_rate','estimated_labor_cost','estimated_additional_cost'].includes(key)}));
    const initial={...project,estimated_hours:Math.floor(project.estimated_minutes/60),estimated_remaining_minutes:project.estimated_minutes%60}; for(const [key,,type] of definitions) if(type==='date')initial[key]=project[key]?.slice(0,10)||'';
    setEditor({title:'Editar projeto',fields,initial,onSave:async values=>{const payload={...values,estimated_minutes:Number(values.estimated_hours||0)*60+Number(values.estimated_remaining_minutes||0)}; for(const [key,value]of Object.entries(payload)){if(parameters.field_access?.[key]?.edit===false)delete payload[key];else if(value==='')payload[key]=null;} await api(request,`/projects/${project.id}`,'PUT',payload);await load();setSelected(null);}});
  }
  async function workflow(project,action) { setEditor({title:action==='finalize'?'Finalizar projeto':action==='reopen'?'Reabrir projeto':'Excluir projeto',fields:[{key:'reason',label:'Justificativa',required:true,minLength:10,maxLength:1000,requiredMessage:'Informe uma justificativa para continuar.',minLengthMessage:'A justificativa deve ter pelo menos 10 caracteres. Explique o motivo da alteração.',help:'Mínimo de 10 caracteres. A justificativa será registrada no histórico de auditoria.'}],initial:{reason:''},onSave:async body=>{await api(request,`/projects/${project.id}${action==='delete'?'':`/${action}`}`,action==='delete'?'DELETE':'POST',body);setSelected(null);await load();}}); }
  function rateEditor(rate={}) { setEditor({title:'Custo/hora',initial:{normal_cost_rate:0,overtime_cost_rate:0,overtime_sale_rate:0,...rate,effective_from:rate.effective_from?.slice(0,10)||'',effective_until:rate.effective_until?.slice(0,10)||''},fields:rateFields.map(f=>f.key==='user_id'?{...f,disabled:!!rate.id,options:(parameters.users||[]).filter(u=>detail?.members?.some(m=>m.user_id===u.id&&m.active))}:f),onSave:async body=>{await api(request,rate.id?`/rates/${rate.id}`:`/projects/${selected.id}/rates`,rate.id?'PUT':'POST',{...body,effective_until:body.effective_until||null});await refresh();}}); }
  function expenseEditor(expense={}) {setEditor({title:'Despesa do projeto',initial:{...expense,expense_date:expense.expense_date?.slice(0,10)||''},fields:[...(access['financial.manage']?[{key:'analyst_id',label:'Analista',options:(parameters.users||[]).filter(u=>detail?.members?.some(m=>m.user_id===u.id&&m.active))}]:[]),{key:'expense_type_id',label:'Tipo de despesa',required:true,options:parameters.expense_types||[]},{key:'expense_date',label:'Data',type:'date',required:true},{key:'description',label:'Descrição',required:true},{key:'amount',label:'Valor',type:'number',min:'0.01',step:'0.01',required:true}],onSave:async body=>{if(!body.analyst_id)delete body.analyst_id;await api(request,expense.id?`/expenses/${expense.id}`:`/projects/${selected.id}/expenses`,expense.id?'PUT':'POST',body);await refresh();}});}
  async function remove(path) {if(!confirm(translateText('Confirmar exclusão?')))return;setBusy(true);try{await api(request,path,'DELETE');await refresh();}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <div className="workspace-page management-workspace"><header className="workspace-heading"><div><span className="workspace-eyebrow">Área de trabalho</span><h1>Gestão de projetos</h1><p>Planejamento, atividades e resultado financeiro.</p></div>{onNewProject&&<button className="primary-action" onClick={onNewProject}>Novo projeto</button>}</header>
    {error&&<p role="alert">{error}</p>}<label>Buscar projeto<input value={search} onChange={e=>setSearch(e.target.value)} /></label>
    <div className="management-table projects-table-wrap"><table><thead><tr><th>Projeto</th><th>Cliente</th><th>Status</th><th>Prazo</th><th>Ações</th></tr></thead><tbody>{projects.filter(p=>`${p.name} ${p.client_name||''}`.toLowerCase().includes(search.toLowerCase())).map(p=><tr className={p.finalized_at?'project-finalized':''} key={p.id}><td><button translate="no" onClick={()=>open(p)}>{p.name}</button></td><td translate="no">{p.client_name||'—'}</td><td>{p.finalized_at?'Finalizado':parameters.project_statuses?.find(s=>s.id===p.project_status_id)?.name||p.status}</td><td>{p.end_date?.slice(0,10)||'—'}</td><td className="management-actions"><button onClick={()=>open(p)}>Detalhes</button>{!p.finalized_at&&access['projects.update']&&<button onClick={()=>editProject(p)}>Editar</button>}{!p.finalized_at&&access['projects.finalize']&&<button onClick={()=>workflow(p,'finalize')}>Finalizar</button>}{p.finalized_at&&access['projects.reopen']&&<button onClick={()=>workflow(p,'reopen')}>Reabrir</button>}{!p.finalized_at&&access['projects.delete']&&<button onClick={()=>workflow(p,'delete')}>Excluir</button>}</td></tr>)}</tbody></table></div>
    {!projects.length&&<p>Nenhum projeto encontrado.</p>}
    {selected&&<section className="management-project-detail"><header className="project-detail-heading"><div><span>Configuração do projeto</span><h2 translate="no">{selected.name}</h2></div><button onClick={()=>setSelected(null)}>Fechar</button></header>{selected.finalized_at&&<p>Projeto finalizado: somente leitura.</p>}
      {detail&&<div className="project-config-grid"><section className="project-config-card"><header><div><h3>Analistas do projeto</h3><p>Profissionais com acesso e participação neste projeto.</p></div>{!selected.finalized_at&&access['projects.update']&&<button className="config-add-button" onClick={()=>setEditor({title:'Atribuir analista',fields:[{key:'user_id',label:'Analista',required:true,options:parameters.users||[]}],initial:{},onSave:async body=>{await api(request,`/projects/${selected.id}/members`,'POST',{...body,role:'analyst'});await refresh();}})}>Atribuir analista</button>}</header><div className="project-member-list">{detail.members?.filter(m=>m.active).map(m=><article key={m.id}><span className="member-initials">{(parameters.users?.find(u=>u.id===m.user_id)?.name||String(m.user_id)).split(' ').map(part=>part[0]).slice(0,2).join('').toUpperCase()}</span><strong translate="no">{parameters.users?.find(u=>u.id===m.user_id)?.name||m.user_id}</strong>{!selected.finalized_at&&access['projects.update']&&<button disabled={busy} onClick={()=>remove(`/projects/${selected.id}/members/${m.user_id}`)}>Remover</button>}</article>)}</div></section>
      {access['financial.manage']&&<><section className="project-config-card full-width"><header><div><h3>Custo/hora dos analistas</h3><p>Valores utilizados no cálculo do resultado financeiro.</p></div>{!selected.finalized_at&&<button className="config-add-button" onClick={()=>rateEditor()}>Adicionar custo/hora</button>}</header>{detail.rates?.length ? <div className="management-table"><table><thead><tr><th>Analista</th><th>Normal</th><th>Extra</th><th>Vigência</th><th>Ações</th></tr></thead><tbody>{detail.rates.map(rate=><tr key={rate.id}><td translate="no">{parameters.users?.find(u=>u.id===rate.user_id)?.name}</td><td>{money(rate.normal_cost_rate)}</td><td>{money(rate.overtime_cost_rate)}</td><td>{rate.effective_from?.slice(0,10)} — {rate.effective_until?.slice(0,10)||'—'}</td><td>{!selected.finalized_at&&<><button onClick={()=>rateEditor(rate)}>Editar</button><button disabled={busy} onClick={()=>remove(`/rates/${rate.id}`)}>Excluir</button></>}</td></tr>)}</tbody></table></div> : <div className="management-empty"><strong>Nenhum custo/hora cadastrado</strong><span>Adicione uma tarifa para calcular o custo das atividades.</span></div>}</section>
      <section className="project-config-card"><header><div><h3>Impostos</h3><p>Tributos aplicados ao valor do contrato.</p></div>{!selected.finalized_at&&parameters.field_access?.taxes?.edit!==false&&<button className="config-add-button" onClick={()=>setEditor({title:'Configurar imposto',fields:[{key:'tax_type_id',label:'Imposto',options:parameters.tax_types||[],required:true},{key:'calculation_type',label:'Cálculo do imposto',required:true,options:[{id:'percentage',name:'Percentual'},{id:'fixed',name:'Valor fixo'}]},{key:'rate',label:'Percentual (%)',type:'number',min:0,max:100,step:'0.0001',required:true},{key:'fixed_amount',label:'Valor fixo',type:'number',min:0,step:'0.01',required:true}],initial:{rate:0,fixed_amount:0,calculation_type:'percentage'},onSave:async body=>{const taxes=(detail.taxes||[]).filter(t=>String(t.tax_type_id)!==String(body.tax_type_id)).map(t=>({tax_type_id:t.tax_type_id,calculation_type:t.calculation_type,rate:t.rate,fixed_amount:t.fixed_amount,calculation_basis:t.calculation_basis}));await api(request,`/projects/${selected.id}/taxes`,'PUT',{taxes:[...taxes,{...body,calculation_basis:'contract_value'}]});await refresh();}})}>Configurar imposto</button>}</header><div className="tax-list">{detail.taxes?.length ? detail.taxes.map(t=><article key={t.id}><div><strong translate="no">{t.type?.name}</strong><span>{t.calculation_type==='fixed'?money(t.fixed_amount):`${t.rate}%`}</span></div>{!selected.finalized_at&&parameters.field_access?.taxes?.edit!==false&&<button onClick={async()=>{if(!confirm(translateText('Confirmar exclusão?')))return;try{await api(request,`/projects/${selected.id}/taxes`,'PUT',{taxes:detail.taxes.filter(x=>x.id!==t.id).map(x=>({tax_type_id:x.tax_type_id,calculation_type:x.calculation_type,rate:x.rate,fixed_amount:x.fixed_amount,calculation_basis:x.calculation_basis}))});await refresh();}catch(e){setError(e.message);}}}>Remover</button>}</article>) : <div className="management-empty compact"><span>Nenhum imposto configurado.</span></div>}</div></section></>}
      </div>}
      <section className="project-expenses"><header><div><h3>Despesas</h3><p>Custos adicionais vinculados ao projeto.</p></div>{!selected.finalized_at&&access['expenses.create']&&<button className="config-add-button" onClick={()=>expenseEditor()}>Adicionar despesa</button>}</header>{expenses.length ? <div className="management-table"><table><thead><tr><th>Descrição</th><th>Valor</th><th>Status</th><th>Ações</th></tr></thead><tbody>{expenses.map(expense=><tr key={expense.id}><td translate="no">{expense.description}</td><td>{money(expense.amount)}</td><td>{expense.status}</td><td>{!selected.finalized_at&&<><button onClick={()=>expenseEditor(expense)}>Editar</button><button disabled={busy} onClick={()=>remove(`/expenses/${expense.id}`)}>Excluir</button>{access['expenses.approve']&&expense.status==='pending'&&<><button onClick={async()=>{try{await api(request,`/expenses/${expense.id}/review`,'POST',{decision:'approved'});await refresh();}catch(e){setError(e.message);}}}>Aprovar</button><button onClick={()=>setEditor({title:'Rejeitar despesa',fields:[{key:'reason',label:'Justificativa',required:true}],initial:{},onSave:async body=>{await api(request,`/expenses/${expense.id}/review`,'POST',{...body,decision:'rejected'});await refresh();}})}>Rejeitar</button></>}</>}</td></tr>)}</tbody></table></div> : <div className="management-empty"><strong>Nenhuma despesa cadastrada</strong><span>As despesas adicionadas ao projeto aparecerão aqui.</span></div>}</section><FinancialResult data={financial}/>
    </section>}{editor&&<Editor {...editor} onClose={()=>setEditor(null)}/>}</div>;
}

const parameterTypes = { clients:'Clientes',project_statuses:'Status do projeto',project_situations:'Situação do projeto',activity_types:'Tipos de atividade',expense_types:'Tipos de despesa',tax_types:'Impostos' };
export function ParametersWorkspace({request,onUsers}) {
  const [type,setType]=useState('clients'),[items,setItems]=useState([]),[access,setAccess]=useState({}),[error,setError]=useState(''),[editor,setEditor]=useState(null),[settings,setSettings]=useState(null),[users,setUsers]=useState([]),[person,setPerson]=useState(''),[permissions,setPermissions]=useState([]),[directory,setDirectory]=useState([]),[nextPage,setNextPage]=useState(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  async function load(){try{setItems(await api(request,`/management/parameters/${type}`));}catch(e){setError(e.message);}}
  useEffect(()=>{let active=true; api(request,'/management/access').then(async a=>{if(!active)return;setAccess(a);if(a['security.manage']){setSettings(await api(request,'/management/settings'));setUsers((await api(request,'/admin/users')).users);}}).catch(e=>setError(e.message));return()=>{active=false;};},[]);
  useEffect(()=>{setError('');load();},[type]);
  function edit(item={}){setEditor({title:parameterTypes[type],fields:[{key:'name',label:'Nome',required:true},{key:'active',label:'Ativo',required:true,options:[{id:'true',name:'Sim'},{id:'false',name:'Não'}]},...(type==='clients'?[{key:'email',label:'E-mail',type:'email'},{key:'phone',label:'Telefone'}]:[])],initial:{...item,active:String(item.active??true)},onSave:async values=>{await api(request,`/management/parameters/${type}${item.id?`/${item.id}`:''}`,item.id?'PUT':'POST',{...values,active:values.active==='true'});await load();}});}
  async function run(action){setBusy(true);setError('');setNotice('');try{await action();}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <div className="workspace-page management-workspace"><header><h1>Cadastros e configurações</h1><p>Parâmetros, responsáveis, permissões e integração Microsoft.</p></header>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
    <div className="management-actions">{Object.entries(parameterTypes).map(([key,label])=><button key={key} className={type===key?'active':''} onClick={()=>setType(key)}>{label}</button>)}{access['security.manage']&&<button onClick={onUsers}>Usuários e responsáveis</button>}</div>
    <h2>{parameterTypes[type]}</h2>{access['parameters.create']&&<button className="primary-action" onClick={()=>edit()}>Adicionar</button>}
    <table><thead><tr><th>Nome</th><th>Status</th><th>Ações</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td translate="no">{item.name}</td><td>{item.active?'Ativo':'Inativo'}</td><td>{access['parameters.update']&&<><button onClick={()=>edit(item)}>Editar</button>{item.active&&<button disabled={busy} onClick={()=>{if(confirm(translateText('Arquivar este cadastro?')))run(async()=>{await api(request,`/management/parameters/${type}/${item.id}`,'DELETE');await load();});}}>Arquivar</button>}</>}</td></tr>)}</tbody></table>
    {access['security.manage']&&<><section><h2>Permissões por usuário</h2><label>Usuário<select value={person} onChange={e=>{const id=e.target.value;setPerson(id);setPermissions([]);if(id)run(async()=>setPermissions(await api(request,`/management/users/${id}/permissions`)));}}><option value="">Selecione</option>{users.map(u=><option key={u.id} value={u.id} translate="no">{u.name}</option>)}</select></label><p>Administradores têm acesso integral. Para os demais, configure cada operação. Campos financeiros seguem as permissões de finanças.</p><div className="management-permissions">{permissions.map(p=><label key={p.id}><input type="checkbox" checked={p.allowed} onChange={e=>setPermissions(permissions.map(item=>item.id===p.id?{...item,allowed:e.target.checked}:item))}/><span translate="no">{p.module}: {p.name}</span></label>)}</div>{person&&<button disabled={busy} onClick={()=>run(async()=>{await api(request,`/management/users/${person}/permissions`,'PUT',{permissions:permissions.map(p=>({id:p.id,allowed:p.allowed}))});setNotice('Permissões salvas.');})}>Salvar permissões</button>}</section>
    {settings&&<section><h2>Retenção de auditoria e Microsoft Entra ID (AAD)</h2><p>Os logs são mantidos por 12 meses por padrão. O agendador do servidor executa a limpeza diária.</p><form onSubmit={e=>{e.preventDefault();run(async()=>{setSettings(await api(request,'/management/settings','PUT',settings));setNotice('Configurações salvas.');});}}><div className="management-fields">{[{key:'audit_retention_months',label:'Retenção (meses)',type:'number',min:1,max:120},{key:'aad_tenant_id',label:'Tenant ID'},{key:'aad_client_id',label:'Application Client ID'},{key:'aad_client_secret',label:settings.aad_secret_configured?'Novo segredo (deixe vazio para manter)':'Client secret',type:'password'}].map(f=><label key={f.key}>{f.label}<input type={f.type||'text'} min={f.min} max={f.max} autoComplete="off" value={settings[f.key]||''} onChange={e=>setSettings({...settings,[f.key]:e.target.value})}/></label>)}</div><button disabled={busy}>Salvar configurações</button></form>
    <p>A listagem do diretório exige permissão Microsoft Graph User.Read.All do tipo Application e consentimento do administrador do tenant.</p><button disabled={busy} onClick={()=>run(async()=>{const result=await api(request,'/management/directory');setDirectory(result.users);setNextPage(result.next);})}>Consultar usuários Microsoft</button>{directory.map(u=><p key={u.id}><span translate="no">{u.displayName} — {u.mail||u.userPrincipalName}</span><button disabled={busy} onClick={()=>run(async()=>{await api(request,'/management/directory/import','POST',{id:u.id});setNotice('Usuário importado como analista. Ajuste o perfil em Usuários e acessos.');})}>Importar como analista</button></p>)}{nextPage&&<button disabled={busy} onClick={()=>run(async()=>{const result=await api(request,`/management/directory?cursor=${encodeURIComponent(nextPage)}`);setDirectory([...directory,...result.users]);setNextPage(result.next);})}>Carregar mais</button>}</section>}</>}
    {editor&&<Editor {...editor} onClose={()=>setEditor(null)}/>}</div>;
}
